apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-th0c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-th0c
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-dotnet60-basic-th0c
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-th0c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-th0c
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:mdsaud-tenant-devfile-sample-dotnet60-basic-th0c
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
