apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-ggse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-ggse
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-go-basic-ggse
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-ggse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-ggse
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:67bcc44f60336bf4deea3761c18877fac79eb17ca2cecb0510080974438ba9da
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
